# The commented lines below come from the RESILIENCY branch for Zipkin & Sleuth.

#spring:
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://localhost:9411}
    
server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewalPercentThreshold: 0.32
    waitTimeInMsWhenSyncEmpty: 0
